version: '3.8'

services:
  cassandra-node1:
    image: cassandra:latest
    container_name: cassandra-node1
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_SEEDS=192.168.1.2
      - CASSANDRA_LISTEN_ADDRESS=192.168.1.2
      - CASSANDRA_BROADCAST_ADDRESS=192.168.1.2
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    restart: on-failure
    networks:
      cassandra-net:
        ipv4_address: 192.168.1.2
    healthcheck:
      test: [ "CMD-SHELL", "nodetool status" ]
      interval: 2m
      start_period: 2m
      timeout: 10s
      retries: 3
    ports:
      - "9042:9042"

  cassandra-node2:
    image: cassandra:latest
    container_name: cassandra-node2
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack2
      - CASSANDRA_SEEDS=192.168.1.2
      - CASSANDRA_LISTEN_ADDRESS=192.168.1.3
      - CASSANDRA_BROADCAST_ADDRESS=192.168.1.3
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    restart: on-failure
    depends_on:
      cassandra-node1:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "nodetool status" ]
      interval: 2m
      start_period: 2m
      timeout: 10s
      retries: 3
    ports:
      - "9043:9042"
    networks:
      cassandra-net:
        ipv4_address: 192.168.1.3

#  cassandra-node3:
#    image: cassandra:latest
#    container_name: cassandra-node3
#    environment:
#      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
#      - CASSANDRA_DC=datacenter1
#      - CASSANDRA_RACK=rack3
#      - CASSANDRA_SEEDS=192.168.1.2
#      - CASSANDRA_LISTEN_ADDRESS=192.168.1.4
#      - CASSANDRA_BROADCAST_ADDRESS=192.168.1.4
#      - CASSANDRA_RPC_ADDRESS=0.0.0.0
#      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
#    restart: on-failure
#    depends_on:
#      cassandra-node2:
#        condition: service_healthy
#    healthcheck:
#      test: [ "CMD-SHELL", "nodetool status" ]
#      interval: 2m
#      start_period: 2m
#      timeout: 10s
#      retries: 3
#    ports:
#      - "9044:9042"
#    networks:
#      cassandra-net:
#        ipv4_address: 192.168.1.4

networks:
  cassandra-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24