spring:
  application:
    name: demo
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: my-consumer-group
      enable-auto-commit: true
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  cassandra:
    contact-points: localhost
    keyspace-name: keyspace_message
    username: cassandra
    password: cassandra
    local-datacenter: datacenter1
    schema-action: create_if_not_exists
    port: 9042
    request:
      consistency: quorum
      timeout: 60s

logging:
  level:
    reactor: ERROR                              # Logs all Reactor actions, such as signals/events
    reactor.util.Loggers: ERROR                 # Detailed logging for Flux/Mono
    com.datastax.oss.driver: ERROR              # Logs Cassandra Java Driver actions
    org.springframework.data.cassandra: TRACE  # Logs Spring Data Cassandra specific events
    com.example.demo: TRACE